Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "eyagizS" do |server|
    server.vm.box = "generic/alpine319"
    server.vm.hostname = "eyagizS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "eyagizS"
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end
end