Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "sciftciS" do |server|
    server.vm.box = "generic/alpine318"
    server.vm.hostname = "sciftciS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "sciftciS"
      v.memory = 512
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end
  
  config.vm.define "sciftciSW" do |worker|
    worker.vm.box = "generic/alpine318"
    worker.vm.hostname = "sciftciSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "sciftciSW"
      v.memory = 512
      v.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
